/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tester;

// import org.junit.jupiter.api.Test;
// import static org.junit.jupiter.api.Assertions.*;

// import java.util.LinkedList;
// import java.util.List;

class AppTest {
    // @Test void appHasAGreeting() {
    //     // App classUnderTest = new App();
    //     // List<String> l = new LinkedList<>();
    //     // assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    // }
}
